import js from '@eslint/js';
import jsdoc from 'eslint-plugin-jsdoc';
import globals from 'globals';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'reports/**',
      '.stryker-tmp/**',
      // Generated by `docs:generate`; ships vendored prettify/linenumber scripts.
      'docs/api/**',
    ],
  },
  js.configs.recommended,
  react.configs.flat.recommended,
  reactHooks.configs.flat.recommended,
  {
    files: ['**/*.{js,jsx,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.webextensions,
        ...globals.jest,
      },
    },
    plugins: {
      jsdoc,
      'react-refresh': reactRefresh,
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      'jsdoc/check-param-names': ['error', { checkDestructured: false }],
      'jsdoc/require-param': ['error', { checkDestructured: false, checkDestructuredRoots: false }],
      'react-refresh/only-export-components': 'warn',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react-hooks/set-state-in-effect': 'warn',
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Error-handling remediation: catch read-modify-write races (require-atomic-updates)
    // and promise executors that return a value, which almost always signals a
    // misunderstanding of the executor's role (no-promise-executor-return). Excludes
    // *.test.{js,jsx,mjs}: measured at ~56 violations there (mostly chrome.storage
    // mock helpers built as `new Promise((resolve) => { chrome.storage.local.set(...,
    // () => resolve(...)) })`), which is test-harness noise, not production risk.
    files: ['src/**/*.{js,jsx,mjs}', 'worker/**/*.{js,jsx,mjs}'],
    ignores: ['**/*.test.{js,jsx,mjs}'],
    rules: {
      'require-atomic-updates': 'error',
      'no-promise-executor-return': 'error',
    },
  },
  {
    // Test helpers carry one-line docblocks for readability, not API docs, and
    // `jsdoc.config.json` excludes them from generation. Keep the two views of
    // "what is documented" in sync.
    files: ['**/*.test.{js,jsx,mjs}'],
    rules: {
      'jsdoc/check-param-names': 'off',
      'jsdoc/require-param': 'off',
    },
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  {
    files: ['src/canvas/App.jsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '../../worker/pipeline/orchestrator.js',
              importNames: ['runPipeline'],
              message:
                'The canvas observes pipeline state; only the background service worker owns runPipeline.',
            },
          ],
        },
      ],
    },
  },
];
