import js from '@eslint/js';
import jsdoc from 'eslint-plugin-jsdoc';
import globals from 'globals';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      'reports/**',
      '.stryker-tmp/**',
      // Generated by `docs:generate`; ships vendored prettify/linenumber scripts.
      'docs/api/**',
    ],
  },
  js.configs.recommended,
  react.configs.flat.recommended,
  reactHooks.configs.flat.recommended,
  {
    files: ['**/*.{js,jsx,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.webextensions,
        ...globals.jest,
      },
    },
    plugins: {
      jsdoc,
      'react-refresh': reactRefresh,
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      'jsdoc/check-param-names': ['error', { checkDestructured: false }],
      'jsdoc/require-param': ['error', { checkDestructured: false, checkDestructuredRoots: false }],
      'react-refresh/only-export-components': 'warn',
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react-hooks/set-state-in-effect': 'warn',
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // `src/shared/runtime/log.js` is the extension's single console boundary;
    // every other module logs through a `createLogger()` instance so the brand
    // prefix and output shape live in one place. Tests may spy on console
    // directly, and `scripts/` are Node build/CI tools whose stdout IS the
    // output, so both stay exempt.
    files: ['src/**/*.{js,jsx,mjs}'],
    ignores: ['**/*.test.{js,jsx,mjs}', 'src/shared/runtime/log.js'],
    rules: {
      'no-console': 'error',
    },
  },
  {
    // Error-handling remediation: catch read-modify-write races (require-atomic-updates)
    // and promise executors that return a value, which almost always signals a
    // misunderstanding of the executor's role (no-promise-executor-return). Excludes
    // *.test.{js,jsx,mjs}: measured at ~56 violations there (mostly chrome.storage
    // mock helpers built as `new Promise((resolve) => { chrome.storage.local.set(...,
    // () => resolve(...)) })`), which is test-harness noise, not production risk.
    files: ['src/**/*.{js,jsx,mjs}'],
    ignores: ['**/*.test.{js,jsx,mjs}'],
    rules: {
      'require-atomic-updates': 'error',
      'no-promise-executor-return': 'error',
    },
  },
  {
    // Test helpers carry one-line docblocks for readability, not API docs, and
    // `jsdoc.config.json` excludes them from generation. Keep the two views of
    // "what is documented" in sync.
    files: ['**/*.test.{js,jsx,mjs}'],
    rules: {
      'jsdoc/check-param-names': 'off',
      'jsdoc/require-param': 'off',
    },
  },
  {
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  {
    // The pipeline's composition root now lives inside the background service
    // worker's own directory, so this boundary is structural: only background
    // code may reach into it. Everything else -- canvas, content, options --
    // observes pipeline state through src/core/pipeline/ instead.
    files: ['src/**/*.{js,jsx,mjs}'],
    ignores: ['src/extension/background/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/extension/background/pipeline/*'],
              message:
                'Only the background service worker owns the pipeline runner and its runtime. Observe pipeline state via src/core/pipeline/ instead.',
            },
          ],
        },
      ],
    },
  },
  {
    // `src/utils/` holds generic, topic-agnostic helpers; `src/domain/` holds
    // the topic model and the projections built on it. The dependency runs
    // domain -> utils only. See ARCHITECTURE_LAYERS.md.
    files: ['src/utils/**/*.js'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/extension/background/pipeline/*'],
              message:
                'Only the background service worker owns the pipeline runner and its runtime. Observe pipeline state via src/core/pipeline/ instead.',
            },
            {
              group: ['**/domain/*'],
              message:
                'src/utils/ must stay topic-agnostic. Topic-specific helpers belong in src/domain/ next to topicDomain.js.',
            },
          ],
        },
      ],
    },
  },
];
